blank_issues_enabled: true
contact_links:
  - name: Support & Questions
    url: https://forum.linuxrenaissance.com/t/how-to-delete-recordings-from-rode-interview-pro-on-linux/42
    about: For usage help, troubleshooting, and general discussion, please use the forum.
