blank_issues_enabled: false
contact_links:
  - name: Support & Questions
    url: https://forum.linuxrenaissance.com/t/how-to-delete-recordings-from-rode-interview-pro-on-linux/42
    about: Please ask support questions on the Linux Renaissance forum, not here.
